### PR TITLE
feat: adding cobra cli

### LINKED ISSUE #9: feat: use cobra
go run cmd/apollo ❌

apollo start --name=deadbeef --num_validators=5  ✅
apollo explorer up ✅

### PR DESCRIPTION
**Pull request by distractedm1nd**
Didn't know where to put main.go/move the other .go files in the root. Do you have a better/cleaner idea? importing apollo/apollo looks kinda dumb

closes #9

### CODE REVIEW

**Review by cmwaters — COMMENTED** [review]
I would still keep all the go files in the root package as is and put the `main.go` file that is used in the cmd directory. 

My tendency is that this repo is primarily to be extended (with the services that the user is building out like `maelstrom`, the shared sequencer) than the command line used as is

**Comment by cmwaters** [comment]
Is `up` and `down` widely used or just in terms of docker containers? i.e. why not use `start` and `stop`?

**Comment by distractedm1nd** [comment]
i used `up` and `down` because I felt like it fit better to network semantics, bringing a network up and down, but I have no strong opinion at all here - would you prefer start/stop?

**Comment by distractedm1nd** [comment]
I've pushed an alternative structure, WDYT?

**Comment by cmwaters** [comment]
Yeah that's better. You need to update the import paths and the README file

**Review by cmwaters — APPROVED** [review]
Is the plan to be able to use the cli to start up and shut down individual services?

**Pull request merged**
